### ISSUE TITLE
Added manual game and the app stopped working.

### ISSUE THREAD

**Issue by sharkiller** [Tormak9970/Steam-Art-Manager#110]
**Describe the bug**
Added a single manual app id and now the app stopped working. 
Added "DiRT Showdown" appid "201700"
Now all buttons stopped working. Restarted app and nothing, not a single app showed and all UI blocked.
Logs read the games but they are never displayed.

Minor bug: also tooltip of adding game say "Manul games" typo. "Add manual games" could be better.

**To Reproduce**
1. Add manual game.
2. App implodes

**Expected behavior**
Work

**Screenshots**
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/0f1b7d0a-82a8-4c92-b647-56909b6b7b60)

**Logs:**
```
[Steam Art Manager] [13:33:1] [INFO]: Initialized logging file
[Steam Art Manager] [13:33:1] [INFO]: Added Steam directory to scope.
[Steam Art Manager] [13:33:1] [INFO]: Initializing CacheController...
[Steam Art Manager] [13:33:1] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [13:33:1] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [13:33:2] [INFO]: Found cache dir.
[Steam Art Manager] [13:33:2] [INFO]: Found grids cache dir.
[Steam Art Manager] [13:33:2] [INFO]: App setup complete.
[Steam Art Manager] [13:33:2] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [13:33:2] [INFO]: Loading non-steam games...
[Steam Art Manager] [13:33:2] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [13:33:2] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [13:33:2] [INFO]: Found Capsule cache dir.
[Steam Art Manager] [13:33:2] [INFO]: Loaded non-steam games.
[Steam Art Manager] [13:33:2] [INFO]: Getting steam games...
[Steam Art Manager] [13:33:2] [INFO]: Getting steam grids folder...
[Steam Art Manager] [13:33:2] [INFO]: Found Wide Capsule cache dir.
[Steam Art Manager] [13:33:2] [INFO]: Found Hero cache dir.
[Steam Art Manager] [13:33:2] [INFO]: Found Logo cache dir.
[Steam Art Manager] [13:33:2] [INFO]: Found Icon cache dir.
[Steam Art Manager] [13:33:2] [INFO]: Initialized CacheController.
[Steam Art Manager] [13:33:2] [INFO]: Grids loaded.
[Steam Art Manager] [13:33:2] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [13:33:3] [INFO]: Library Cache loaded.
[Steam Art Manager] [13:33:3] [INFO]: Cached logo positions for 10 games.
[Steam Art Manager] [13:33:3] [INFO]: Loading games from Steam API...
[Steam Art Manager] [13:33:3] [INFO]: Loaded 751 games from Steam API.
[Steam Art Manager] [13:33:3] [INFO]: Steam games loaded.
```

**System information (please complete the following information):**
 - OS: Win 10 pro
 - v2.6.0

**Additional information**
Add any other information about the problem here.

**Comment by Tormak9970** [comment]
Yikes, I will look into this when I have a chance. The reason for the tooltip is the window also allows you to remove manual games. I will try and clarify that in both the tooltip and the labels in the window itself.

**Comment by Tormak9970** [comment]
Issue should be fixed. Please try the most recent debug release found [here](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/debug-2.6.0)

**Comment by Tormak9970** [comment]
shoot. i suspect this is related to #97
