### ISSUE TITLE
Include shared games

### ISSUE THREAD

**Issue by JelledFro** [Tormak9970/Steam-Art-Manager#117]
As far as I can tell the game list doesn't include games you have access to through library sharing with friends. It would be great if they could be! Right now I can only customize the art of around two thirds of my library with this program.

**Comment by Tormak9970** [comment]
given that its shared, are you able to select whoever shared it with you from the user dropdown?

**Comment by Tormak9970** [comment]
closing this as there doesn't seem to be a reliable way to find these. There's a feature to manually add games already in SARM, and once the SGDB api gets an update, you will be able to search for the games using the SGDB api which will make the process much faster
