### ISSUE TITLE
Allow searching for a custom title

### ISSUE THREAD

**Issue by traysh** [Tormak9970/Steam-Art-Manager#141]
**Describe the feature you'd like**
It would be great if I could search for a custom title, not only the title set on Steam.

**Please provide context on why you'd like this**
This is because I have games with longs titles in my library that I added with a shortened version and now I can't fetch artwork for them.

**Comment by Tormak9970** [comment]
> **Describe the feature you'd like** It would be great if I could search for a custom title, not only the title set on Steam.
> 
> **Please provide context on why you'd like this** This is because I have games with longs titles in my library that I added with a shortened version and now I can't fetch artwork for them.

I can look at trying to add this. I'll add it if I can find a good way to integrate it into the UI. To clarify, you mean you've added non-steam games with shortened names?

**Comment by traysh** [comment]
I did, or names that make sense to me but are not official.

2 examples:

Given name: Savage
Real name: Worlds of Ultima: the Savage Empire
Problem: can't find the right artwork, maybe because "savage" is present in
too many game titles

Given name: Launch desktop
Real name: KDE Plasma 5
Problem: the name I gave has no relation with the app name, so I can't find
the artwork

**Comment by Tormak9970** [comment]
this has been implemented in https://github.com/Tormak9970/Steam-Art-Manager/commit/605997be226f8532be4ee53a19e12837e7b43d40 and will be included in the next release
