### ISSUE TITLE
Any chance for a MacOS version?

### ISSUE THREAD

**Issue by lothar-cell** [Tormak9970/Steam-Art-Manager#150]
**Describe the feature you'd like**
I'd like a Mac version.

**Please provide context on why you'd like this**
Currently artwork replacement can only be done manually on MacOS, and since there's a Linux build already, it wouldn't be too far to make it run under a Mac.

**Comment by Tormak9970** [comment]
> **Describe the feature you'd like**
> I'd like a Mac version.
> 
> **Please provide context on why you'd like this**
> Currently artwork replacement can only be done manually on MacOS, and since there's a Linux build already, it wouldn't be too far to make it run under a Mac.
> 

Unfortunately its not that easy. It would require a decent amount of work, which I am happy to do except for the fact that I don't own a mac. Because of that, I can't debug Mac builds, so I have refrained from providing that option

**Comment by lothar-cell** [comment]
A virtual machine maybe?

**Comment by Tormak9970** [comment]
As far as I'm aware, MacOS VM's are either very unreliable, or very expensive, so that's not a viable solution imo

**Comment by lothar-cell** [comment]
What I meant is eg. Virtual Box: https://www.virtualbox.org/

**Comment by Tormak9970** [comment]
> What I meant is eg. Virtual Box: https://www.virtualbox.org/

From what I know virtual box does not support running MacOS VMs
