### ISSUE TITLE
Games marked as "Private" don't show up when searched for it

### ISSUE THREAD

**Issue by Archilyte** [Tormak9970/Steam-Art-Manager#151]
**Describe the bug**
Steam Art Manager can't detect "Private" games

**To Reproduce**
1. Enable the beta version of the Steam client
2. Right click on any game and set it to private
3. Try to search up that game on Steam Art Manager

**Expected behavior**
Game shows up when searched for it.

**Additional information**
[This](https://help.steampowered.com/en/faqs/view/1150-C06F-4D62-4966) has more info about marking games as "Private"

**Comment by Tormak9970** [comment]
I need to look into this but I suspect that the steam api just do4snt return private games. If so I won't be able to do anything about it

**Comment by Tormak9970** [comment]
@Archilyte have you put in a Steam API key? I tested making a game private and it still shows up. Its also possible one of the changes I've made since the last release fixed whatever is causing the issue

**Comment by Archilyte** [comment]
ok it seems to be working after giving the steam api key! thank you!
