### ISSUE TITLE
Sourcemods and Goldsrc mods

### ISSUE THREAD

**Issue by ColossusSteppes** [Tormak9970/Steam-Art-Manager#152]
(Unless I'm missing a setting) SARM doesn't seem to detect any games in the \steam\steamapps\sourcemods folder, nor does it pick up any Half-Life 1 mods in \steamapps\common\half-life\

Usually adding sourcemods or goldsrcmods to these folders and restarting Steam will make them appear in your library.

Would it be possible to add these in the future? I know that adding new sourcemods has a tendancy to shuffle around the ids so the art also gets shuffled around with different sourcemods, so I'm not sure if that would also be an issue with this.

**Comment by Tormak9970** [comment]
@ColossusSteppes could you give some examples of how you would manually set art for sourcemods and goldsrc mods? I don't have a way to test these, and yes, the id shuffling would likely still cause issues

**Comment by ColossusSteppes** [comment]
@Tormak9970 Sorry, I'm not entirely sure what you mean. When adding sourcemods to the \Steam\steamapps\sourcemods\ folder and restarting Steam, they appear in my library and I can edit their artwork manually like any other game.

**Comment by Tormak9970** [comment]
> @Tormak9970 Sorry, I'm not entirely sure what you mean. When adding sourcemods to the \Steam\steamapps\sourcemods\ folder and restarting Steam, they appear in my library and I can edit their artwork manually like any other game.

Ahh I see. I'll try to install some myself and do some testing

**Comment by ColossusSteppes** [comment]
@Tormak9970 Oh, forgot to mention that Goldsrc mods are installed differently. For example, Half-Life mods go in the \steamapps\common\Half-Life\ folder. I've got "Echoes" and "Field Intensity" installed here. This also requires a restart of Steam before they show in your library.
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/106880608/234cfbc3-fc56-48a9-a9b9-763714f11f32)

**Comment by Tormak9970** [comment]
> @Tormak9970 Oh, forgot to mention that Goldsrc mods are installed differently. For example, Half-Life mods go in the \steamapps\common\Half-Life\ folder. I've got "Echoes" and "Field Intensity" installed here. This also requires a restart of Steam before they show in your library. ![image](https://private-user-images.githubusercontent.com/106880608/317777599-234cfbc3-fc56-48a9-a9b9-763714f11f32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzkwODQsIm5iZiI6MTcxMTYzODc4NCwicGF0aCI6Ii8xMDY4ODA2MDgvMzE3Nzc3NTk5LTIzNGNmYmMzLWZjNTYtNDhhOS1hOWI5LTc2MzcxNGYxMWYzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxNTEzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjdlY2NmNzkyZjYyNDQwNzdiZmE2YzNiYmMzZDk2NTIwYjViNmIyYjAyZWQ2ZTEzZmQzNDI1MWU3YzgzODNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tMfaOg7ZIh57IWQMkdkzlvvRS-HurUpAgmqNZNcYhSs)

hmm, that screenshot is helpful. I just need to figure out how steam calculates the id it should use for them

**Comment by Tormak9970** [comment]
There does not appear to be a way to determine the appid of sourcemods and goldsrc mods, which means I can't include them unfortunately

**Comment by ColossusSteppes** [comment]
That's a shame, but thank you for looking into it!
