### ISSUE TITLE
windows Tile

### ISSUE THREAD

**Issue by jtesjh** [Tormak9970/Steam-Art-Manager#153]
**Describe the feature you'd like**
I would like to add custom tiles to win10

**Please provide context on why you'd like this**
Most of the tiles I've found only support exe, lnk, etc. but not steam's steam://run link, and working manually is too cumbersome, you have to export the url first, then convert the downloaded jpg or png to ico, add the url you got to the ico you just converted, transfer it to the directory where the start menu is located, and then finally press the Finally, press win to look in the directory and right click to get the modified tile, I hope you can speed up this process. I hope you can speed up the process.
By the way, I've attached my screenshots (of which only the 'genshin impact' has been modified)
https://smms.app/image/RtljYL9hasg5WGI

**Comment by Tormak9970** [comment]
> **Describe the feature you'd like**
> I would like to add custom tiles to win10
> 
> **Please provide context on why you'd like this**
> Most of the tiles I've found only support exe, lnk, etc. but not steam's steam://run link, and working manually is too cumbersome, you have to export the url first, then convert the downloaded jpg or png to ico, add the url you got to the ico you just converted, transfer it to the directory where the start menu is located, and then finally press the Finally, press win to look in the directory and right click to get the modified tile, I hope you can speed up this process. I hope you can speed up the process.
> By the way, I've attached my screenshots (of which only the 'genshin impact' has been modified)
> [https://smms.app/image/RtljYL9hasg5WGI](url)
> 

This sounds really interesting. Can you clarify what you mean by "tile"? Also how does steam://run come into play? Are you referring to like the icons in the start menu?

**Comment by jtesjh** [comment]
Maybe it's because I'm translating this sentence through deepl all a bit unclear (my native language is not English)

And I was saying "MOST of the Tiles've Found Found only Only Support Exe, LNK, ETC.", the "Tiles" that I want to express is actually the program that creates Tiles

"Steam: // Run" is a link that can quickly open the Steam game through "Win+R" or browser. It can usually be found in the shortcut created by Steam, so its suffix is. URL instead of .lnk

What is a window tile? 
A tile is an app's representation on the Start menu. Every app has a tile. When you create a new Windows app project in Microsoft Visual Studio, it includes a default tile that displays your app's name and logo. Windows displays this tile when your app is first installed.   --https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/creating-tiles

**Comment by jtesjh** [comment]
> > **描述您想要的功能 **
> > 我想为 win10 添加自定义磁贴 
> > **请提供背景说明您为何需要此功能 **我发现的大多数图块只支持exe、lnk等，而不支持steam的steam://run链接，而且手动操作太麻烦，必须先导出url，然后将下载的jpg或png转换为ico ，将你得到的url添加到你刚刚转换的ico中，传输到开始菜单所在的目录，然后最后按win在目录中查找，右键单击以获得修改后的图块，我希望你可以加快这个过程。  我希望你能加快这个过程。 
> > 顺便说一下，我附上了我的截图（其中只有“原神影响”已被修改） 
> > [https://smms.app/image/RtljYL9hasg5WGI ](url)
> 
> 这听起来真的很有趣。 您能澄清一下“瓷砖”的含义吗？ steam://run 又是如何发挥作用的？ 您指的是开始菜单中的图标吗？

Maybe it's because I'm translating this sentence through deepl all a bit unclear (my native language is not English)

And I was saying "MOST of the Tiles've Found Found only Only Support Exe, LNK, ETC.", the "Tiles" that I want to express is actually the program that creates Tiles

"Steam: // Run" is a link that can quickly open the Steam game through "Win+R" or browser. It can usually be found in the shortcut created by Steam, so its suffix is. URL instead of .lnk

What is a window tile? 
A tile is an app's representation on the Start menu. Every app has a tile. When you create a new Windows app project in Microsoft Visual Studio, it includes a default tile that displays your app's name and logo. Windows displays this tile when your app is first installed.   --https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/creating-tiles

**Comment by Tormak9970** [comment]
> > > **描述您想要的功能 **
> > > 我想为 win10 添加自定义磁贴
> > > **请提供背景说明您为何需要此功能 **我发现的大多数图块只支持exe、lnk等，而不支持steam的steam://run链接，而且手动操作太麻烦，必须先导出url，然后将下载的jpg或png转换为ico ，将你得到的url添加到你刚刚转换的ico中，传输到开始菜单所在的目录，然后最后按win在目录中查找，右键单击以获得修改后的图块，我希望你可以加快这个过程。  我希望你能加快这个过程。
> > > 顺便说一下，我附上了我的截图（其中只有“原神影响”已被修改）
> > > [https://smms.app/image/RtljYL9hasg5WGI ](url)
> > 
> > 
> > 这听起来真的很有趣。 您能澄清一下“瓷砖”的含义吗？ steam://run 又是如何发挥作用的？ 您指的是开始菜单中的图标吗？
> 
> Maybe it's because I'm translating this sentence through deepl all a bit unclear (my native language is not English)
> 
> And I was saying "MOST of the Tiles've Found Found only Only Support Exe, LNK, ETC.", the "Tiles" that I want to express is actually the program that creates Tiles
> 
> "Steam: // Run" is a link that can quickly open the Steam game through "Win+R" or browser. It can usually be found in the shortcut created by Steam, so its suffix is. URL instead of .lnk
> 
> What is a window tile? A tile is an app's representation on the Start menu. Every app has a tile. When you create a new Windows app project in Microsoft Visual Studio, it includes a default tile that displays your app's name and logo. Windows displays this tile when your app is first installed. --https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/creating-tiles

ah, interesting. I can definitely look into adding a system to try and automate setting the tiles to the selected icons. Do you have a reference to how you would edit that manually?

**Comment by jtesjh** [comment]
> > > > **描述您想要的功能 **
> > > > 我想为 win10 添加自定义磁贴
> > > > **请提供背景说明您为何需要此功能 **我发现的大多数图块只支持exe、lnk等，而不支持steam的steam://run链接，而且手动操作太麻烦，必须先导出url，然后将下载的jpg或png转换为ico ，将你得到的url添加到你刚刚转换的ico中，传输到开始菜单所在的目录，然后最后按win在目录中查找，右键单击以获得修改后的图块，我希望你可以加快这个过程。  我希望你能加快这个过程。
> > > > 顺便说一下，我附上了我的截图（其中只有“原神影响”已被修改）
> > > > [https://smms.app/image/RtljYL9hasg5WGI ](url)
> > > 
> > > 
> > > 这听起来真的很有趣。 您能澄清一下“瓷砖”的含义吗？ steam://run 又是如何发挥作用的？ 您指的是开始菜单中的图标吗？
> > 
> > 
> > Maybe it's because I'm translating this sentence through deepl all a bit unclear (my native language is not English)也许是因为我通过deepl翻译这句话有点不清楚（我的母语不是英语）
> > And I was saying "MOST of the Tiles've Found Found only Only Support Exe, LNK, ETC.", the "Tiles" that I want to express is actually the program that creates Tiles我说“大多数 Tiles 已经找到的只支持 Exe、LNK 等”，我想表达的“Tiles”实际上是创建 Tiles 的程序
> > "Steam: // Run" is a link that can quickly open the Steam game through "Win+R" or browser. It can usually be found in the shortcut created by Steam, so its suffix is. URL instead of .lnk“Steam： // Run”是一个可以通过“Win+R”或浏览器快速打开Steam游戏的链接。它通常可以在 Steam 创建的快捷方式中找到，因此它的后缀是。URL 而不是 .lnk
> > What is a window tile? A tile is an app's representation on the Start menu. Every app has a tile. When you create a new Windows app project in Microsoft Visual Studio, it includes a default tile that displays your app's name and logo. Windows displays this tile when your app is first installed. --https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/creating-tiles什么是窗砖？磁贴是应用在“开始”菜单上的表示形式。每个应用都有一个磁贴。在 Microsoft Visual Studio 中创建新的 Windows 应用项目时，它包含一个默认磁贴，用于显示应用的名称和徽标。Windows 在首次安装应用时显示此磁贴。-- https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/creating-tiles
> 
> ah, interesting. I can definitely look into adding a system to try and automate setting the tiles to the selected icons. Do you have a reference to how you would edit that manually?啊，有意思。我绝对可以考虑添加一个系统来尝试自动将磁贴设置为选定的图标。您是否有关于如何手动编辑的参考？

Steam-Tiles https://github.com/pepeizq/Steam-Tiles :Tiles software for steam
Tile Genie http://tilegenie.blogspot.com/ :Tiles software for pictures
TileTool https://github.com/XIU2/TileTool :Tiles software for software and shortcuts
web tiles https://apps.microsoft.com/detail/9NBLGGH4VG9C?hl=es-pa&gl=PA  :Tiles software for web pages

**Comment by Tormak9970** [comment]
These are great resources! Thank you. I think I should be able to implement it by converting the icon types to ones that can be used for tiles

**Comment by jtesjh** [comment]
> These are great resources! Thank you. I think I should be able to implement it by converting the icon types to ones that can be used for tiles

Thank you.

**Comment by Tormak9970** [comment]
complete as of https://github.com/Tormak9970/Steam-Art-Manager/commit/f8d80e54294635820ed5e34776d72fa2573f0662
