### ISSUE TITLE
New Update cannot detect Steam (deb) default path

### ISSUE THREAD

**Issue by dtantono** [Tormak9970/Steam-Art-Manager#160]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.2.0
2. Download the Appimage file
3. Double click the file
4. it shows nothing

**Expected behavior**
it should shows the file

**Screenshots**
![2024-03-17_10-10](https://github.com/Tormak9970/Steam-Art-Manager/assets/29157187/d1079185-41ce-49da-9c5a-0eb42fb57bfd)

**Logs:**
[core.log](https://github.com/Tormak9970/Steam-Art-Manager/files/14625774/core.log)

**System information (please complete the following information):**
 - OS: Kubuntu 22.04 LTS
 - Version 2.3.2

**Additional information**
I tried to set it manually it to default steam path and restart the app. But, it does not worked

**Comment by Tormak9970** [comment]
@dtantono does v3.0.0 work?

**Comment by Tormak9970** [comment]
also can you provide what the install path is?

**Comment by dtantono** [comment]
yeah, downgrading does not work either and if you mean Steam Installation path. the path is /home/user/.steam/steam/. what do you think?
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/29157187/c0df94a4-a364-42d8-8fbc-e3bc5c78bda9)

**Comment by Tormak9970** [comment]
Hmm, odd, it should be able to find that. What distro are you using and can you share your settings.json file? (Remove your api keys from it tho)

**Comment by Tormak9970** [comment]
@dtantono can you try the new debug release https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/debug-3.2.0, I think it may address your issue

**Comment by dtantono** [comment]
<img width="641" alt="image" src="https://github.com/Tormak9970/Steam-Art-Manager/assets/29157187/38e7942e-1ffd-4ad4-931a-294430cc5854">
Finally, it can detect my username. But, the games are not loaded

**Comment by Tormak9970** [comment]
Can you right click and choose inspect and screenshot that window?

**Comment by dtantono** [comment]
<img width="945" alt="image" src="https://github.com/Tormak9970/Steam-Art-Manager/assets/29157187/a699af5c-aba6-4650-bcdd-b717a6bb6925">

**Comment by dtantono** [comment]
<img width="930" alt="image" src="https://github.com/Tormak9970/Steam-Art-Manager/assets/29157187/66ee84cd-251c-4715-b183-ba650f68e7f8">

**Comment by Tormak9970** [comment]
Can you check to see if you made a typo in your steamAPI key? Looks like that might be the issue

**Comment by dtantono** [comment]
yes, it works. Thanks

**Comment by Tormak9970** [comment]
Ok good to know. I need to add a check for miss entered keys
