### ISSUE TITLE
SARM doesn't launch after being installed

### ISSUE THREAD

**Issue by okamitime** [Tormak9970/Steam-Art-Manager#171]
**Describe the bug**
SARM refuses to launch after installation.

**To Reproduce**
1. Install SARM using the msi file
2. Double click on executable

**Expected behavior**
SARM will launch

**Screenshots**
N/A

**Logs:**
No log file is created.

**System information**
 - OS: Windows 10
 - Version: v.3.6.0

**Additional information**
Steam is already installed and has been launched previously

**Comment by Tormak9970** [comment]
> **Describe the bug**
> 
> SARM refuses to launch after installation.
> 
> 
> 
> **To Reproduce**
> 
> 1. Install SARM using the msi file
> 
> 2. Double click on executable
> 
> 
> 
> **Expected behavior**
> 
> SARM will launch
> 
> 
> 
> **Screenshots**
> 
> N/A
> 
> 
> 
> **Logs:**
> 
> No log file is created.
> 
> 
> 
> **System information**
> 
>  - OS: Windows 10
> 
>  - Version: v.3.6.0
> 
> 
> 
> **Additional information**
> 
> Steam is already installed and has been launched previously
> 
> 

Can you elaborate? From what I understand you installed SARM, then tried to run the .exe? Do the shortcuts still work, or are they broken too?

**Comment by Tormak9970** [comment]
Closing as this is not reproduceable

**Comment by okamitime** [comment]
> From what I understand you installed SARM, then tried to run the .exe?
I first tried launching from the dialog on the installer, and then I tried clicking the desktop shortcut that was created after installation. Neither open SARM.

**Comment by Tormak9970** [comment]
> > From what I understand you installed SARM, then tried to run the .exe?
> 
> I first tried launching from the dialog on the installer, and then I tried clicking the desktop shortcut that was created after installation. Neither open SARM.

do you have an anti virus installed?

**Comment by okamitime** [comment]
I have my antivirus program turned off.

**Comment by Tormak9970** [comment]
@okamitime I tested a clean install and it seems to work properly. Can you check to see if `C:\Users\YOUR_USERNAME\AppData\Roaming\dev.tormak.steam-art-manager\logs\core.log` exists, and if so, what the contents are? Also, could you try installing [v3.2.1](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.2.1)? If that does not work, its definitely a windows issue

**Comment by okamitime** [comment]
>C:\Users\YOUR_USERNAME\AppData\Roaming\dev.tormak.steam-art-manager\logs\core.log

Strangely there's no folder with the name `dev.tormak.steam-art-manager` in this location. I took a peek in %localappdata% and there's a folder with that name that is created after installation (nothing inside though, not even an empty logs subfolder)
I tried installing the latest version v3.6.4 as well as the version you mentioned but same thing.

**Comment by Tormak9970** [comment]
> >C:\Users\YOUR_USERNAME\AppData\Roaming\dev.tormak.steam-art-manager\logs\core.log
> 
> 
> 
> Strangely there's no folder with the name `dev.tormak.steam-art-manager` in this location. I took a peek in %localappdata% and there's a folder with that name that is created after installation (nothing inside though, not even an empty logs subfolder)
> 
> I tried installing the latest version v3.6.4 as well as the version you mentioned but same thing.

Ok so that means its just making it through the installer. And since that old version doesn't work, its likely a windows issue, not a SARM one. Have you had this problem with other .msi installers?

**Comment by okamitime** [comment]
Figured out the problem! So I installed the first version of SARM which allowed me to view a command prompt window that popped up and disappeared quickly after installation. In short, I wasn't able to open SARM due to not having Webview2 installed. After reinstalling that I was able to launch successfully.
