### ISSUE TITLE
Will not load new images, if window is large enough to display initial load

### ISSUE THREAD

**Issue by Furglitch** [Tormak9970/Steam-Art-Manager#172]
**Describe the bug**
Fails to load additional images when the window is large enough to display all currently loaded images.

**To Reproduce**
- Ensure the window is large enough to display all images from the initial load (maximum of 42 images when fullscreen at 1440p).
- No additional images load beyond the initial set.
- Resize the window to a smaller size, causing a scrollbar to appear.
- Scroll down to load more images.
- Optionally, resize to fullscreen again
- Since more images are loaded, scroll bar is present, and more images can be loaded in fullscreen.

**Expected behavior**
Expected SARM to load all images, regardless of window size, without the need to resize the window to trigger additional image loading.

**Logs**
[core.log](https://github.com/Tormak9970/Steam-Art-Manager/files/15020953/core.log)
Don't think there's much relevant. It just shows the images being pulled once I'm able to scroll.

**Screen Recording**
https://streamable.com/nanb0j
I tested with "Overwatch 2" as an example

**System information (please complete the following information):**
 - OS: Windows 11
 - Version 3.6.0

**Comment by Tormak9970** [comment]
Didn't think about this. Will fix when I have a chance

**Comment by Tormak9970** [comment]
fixed as of https://github.com/Tormak9970/Steam-Art-Manager/commit/83d6708ee7e1e4e9fdab5a877c258cfea99f4de8
