### ISSUE TITLE
Cant input SteamGridDB api key

### ISSUE THREAD

**Issue by anopem** [Tormak9970/Steam-Art-Manager#175]
Cant input SteamGridDB api key, it says the key is invalid even though i try and revoke the old and input the new

**Comment by Tormak9970** [comment]
> Cant input SteamGridDB api key, it says the key is invalid even though i try and revoke the old and input the new

I'll look into it but can you confirm you've copied the whole key when you're testing it?

**Comment by Dogo314** [comment]
Same issue here. Even if a new API key is created the issue persists.

**Comment by anopem** [comment]
> > Cant input SteamGridDB api key, it says the key is invalid even though i try and revoke the old and input the new
> 
> I'll look into it but can you confirm you've copied the whole key when you're testing it?

I definetly did, even checked the dev tool to be extra sure

**Comment by Tormak9970** [comment]
@anopem @Dogo314 A new release will be available shortly. I believe the issue should be fixed, but let me know if its not

**Comment by anopem** [comment]
@Tormak9970 That fixed it
