### ISSUE TITLE
Filter changes are not being saved

### ISSUE THREAD

**Issue by anopem** [Tormak9970/Steam-Art-Manager#180]
I would like an option to remember tags so that i wont have to enable NSFW and Epilepsy every time on every category

**Comment by Tormak9970** [comment]
it should already save your filters. I'll look into why it aint workin

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/Steam-Art-Manager/commit/bf054d8d84769c41e2244759448869835dd33eaa. It'll be included in the next release
