### ISSUE TITLE
Images unloading or duplicating

### ISSUE THREAD

**Issue by Furglitch** [Tormak9970/Steam-Art-Manager#181]
**Describe the bug**
When loading grids, some will occasionally unload, or duplicates will be loaded. The issue is intermittent. Doesn't happen with every game. Sometimes duplicates will only be of a few grids, sometimes every grid that's already loaded.

**To reproduce**
With it being intermittent, there's not much to do aside from loading games and seeing if grids that appear are unloaded or duplicated when loading more.

**Screenshots**
Unloading grids - https://streamable.com/jqmlzf - It's difficult to see, as it's right at the beginning of the video. The grids that are initially loaded disappear and are not viewable. (i.e. tscar's grid)
Duplicate grids - https://streamable.com/43y2s6 - The list of available grids repeats when the next section is loaded. I gesture towards the duplicates.

**Logs:**
Please upload/paste the contents of your log file (you should remove any sensitive information like keys).
[core.log](https://github.com/Tormak9970/Steam-Art-Manager/files/15215255/core.log)

**System information (please complete the following information):**
 - OS: Windows 11
 - Version 3.6.2

Perhaps making a temporary cache of grid ids and running a check when fetching can resolve this.

**Comment by Tormak9970** [comment]
> **Describe the bug**
> 
> When loading grids, some will occasionally unload, or duplicates will be loaded. The issue is intermittent. Doesn't happen with every game. Sometimes duplicates will only be of a few grids, sometimes every grid that's already loaded.
> 
> 
> 
> **To reproduce**
> 
> With it being intermittent, there's not much to do aside from loading games and seeing if grids that appear are unloaded or duplicated when loading more.
> 
> 
> 
> **Screenshots**
> 
> Unloading grids - https://streamable.com/jqmlzf - It's difficult to see, as it's right at the beginning of the video. The grids that are initially loaded disappear and are not viewable. (i.e. tscar's grid)
> 
> Duplicate grids - https://streamable.com/43y2s6 - The list of available grids repeats when the next section is loaded. I gesture towards the duplicates.
> 
> 
> 
> **Logs:**
> 
> Please upload/paste the contents of your log file (you should remove any sensitive information like keys).
> 
> [core.log](https://github.com/Tormak9970/Steam-Art-Manager/files/15215255/core.log)
> 
> 
> 
> **System information (please complete the following information):**
> 
>  - OS: Windows 11
> 
>  - Version 3.6.2
> 
> 
> 
> Perhaps making a temporary cache of grid ids and running a check when fetching can resolve this.

Its probably an issue with the new loading system, I'll look into it

**Comment by Tormak9970** [comment]
This was one of the most confusing things I've had to debug. Turned out to be a weird side effect of how I render the grids. Fixed it in https://github.com/Tormak9970/Steam-Art-Manager/commit/c9c3e9f28333c242c8893337f96e268a124d7833. It'll be included in the new release.
