### ISSUE TITLE
Crash and then no longer recognizes Steam install

### ISSUE THREAD

**Issue by kdliu86** [Tormak9970/Steam-Art-Manager#187]
Using 3.6.4

1. Open SARM
2. Fill in API keys
3. Click Non Steam
4. Click Edit (category), select a game title.
5. Pop up/toast CHOICE APPLIED!
6. App hangs here.

Force close SARM
1. Open SARM
2. SARM asks for Steam install this time around, does not recognize Steam deck default folder.

```
[Steam Art Manager] [22:23:20] [INFO]: Initialized logging file
[Steam Art Manager] [22:23:21] [INFO]: Initializing CacheController...
[Steam Art Manager] [22:23:21] [INFO]: Found cache dir.
[Steam Art Manager] [22:23:21] [INFO]: Found grids cache dir.
[Steam Art Manager] [22:23:21] [INFO]: Found Capsule cache dir.
[Steam Art Manager] [22:23:21] [INFO]: Finished checking settings for new app version and/or migration.
[Steam Art Manager] [22:23:21] [INFO]: Added /home/deck/.local/share/Steam to scope.
[Steam Art Manager] [22:23:21] [INFO]: Found Wide Capsule cache dir.
[Steam Art Manager] [22:23:21] [WARNING]: Error canonicalizing /home/deck/.local/share/steam: No such file or directory (os error 2).
[Steam Art Manager] [22:23:21] [WARNING]: Steam Not Found
[Steam Art Manager] [22:23:21] [INFO]: Found Hero cache dir.
[Steam Art Manager] [22:23:21] [INFO]: Found Logo cache dir.
[Steam Art Manager] [22:23:21] [INFO]: Found Icon cache dir.
[Steam Art Manager] [22:23:21] [INFO]: Initialized CacheController.
[Steam Art Manager] [22:24:35] [WARNING]: Error canonicalizing ~/.steam/steam: No such file or directory (os error 2).

```

Does the app need certain folder access privileges?  I'm not sure where to go to turn them on, I can see all folders in Dolphin.

Interestingly enough, from the install script. 2.9.0 and 3.0.0 work fine.

**Comment by Tormak9970** [comment]
@kdliu86 Nah it doesn't need special folder perms, its been having some trouble lately because of how steam does symlinks. I believe I've fixed it but need to do some testing before I make another release

**Comment by Tormak9970** [comment]
App hang was fixed with https://github.com/Tormak9970/Steam-Art-Manager/commit/b6ba640e95859f2d06c67324f477fb1017f75be7 and

**Comment by Tormak9970** [comment]
Closing this as now it is the same problem as #188
