### ISSUE TITLE
Not finding images

### ISSUE THREAD

**Issue by anopem** [Tormak9970/Steam-Art-Manager#190]
When selecting different games the grid list says it finds no results but i have previously changed the same game with many images loading and theres plenty of images on SGDB for it aswell

This error was in console
`main-072727c9.js:24  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'Capsule')
    at k (main-072727c9.js:24:35928)`

**Comment by Tormak9970** [comment]
> When selecting different games the grid list says it finds no results but i have previously changed the same game with many images loading and theres plenty of images on SGDB for it aswell
> 
> 
> 
> 
> 
> This error was in console
> 
> `main-072727c9.js:24  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'Capsule')
> 
>     at k (main-072727c9.js:24:35928)`

What version is this? Is it the debug version or the latest stable release?

**Comment by anopem** [comment]
> > When selecting different games the grid list says it finds no results but i have previously changed the same game with many images loading and theres plenty of images on SGDB for it aswell
> > This error was in console
> > `main-072727c9.js:24  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'Capsule')
> > ```
> > at k (main-072727c9.js:24:35928)`
> > ```
> 
> What version is this? Is it the debug version or the latest stable release?

Where would i see that? but i just updated it

**Comment by Tormak9970** [comment]
> > > When selecting different games the grid list says it finds no results but i have previously changed the same game with many images loading and theres plenty of images on SGDB for it aswell
> 
> > > This error was in console
> 
> > > `main-072727c9.js:24  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'Capsule')
> 
> > > ```
> 
> > > at k (main-072727c9.js:24:35928)`
> 
> > > ```
> 
> > 
> 
> > What version is this? Is it the debug version or the latest stable release?
> 
> 
> 
> Where would i see that? but i just updated it
> 
> 
> 
> edit:
> 
> nvm its at the top 3.6.4

Ok awesome. I'll look into this

**Comment by Furglitch** [comment]
+1 but with no console error, just `[Steam Art Manager] [22:47:23] [INFO]: Query: "Wide Capsules for Skyrim Script Extender (SKSE)". Result: no grids.` and similar for most games

**Comment by spineduke** [comment]
Facing the same issue, no images found

**Comment by Tormak9970** [comment]
@spineduke @anopem @Furglitch I'm having trouble reproducing this after making some other fixes, so I've released those fixes in [v3.6.5](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.6.5). Can yall test this again with the new update and let me know if the issue persists?

**Comment by anopem** [comment]
> @spineduke @anopem @Furglitch I'm having trouble reproducing this after making some other fixes, so I've released those fixes in [v3.6.5](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.6.5). Can yall test this again with the new update and let me know if the issue persists?

Unfortunetly it still persists for me, checked some works but didnt work for Back 4 Blood, Crysis 2 Remastered, Frostpunk

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/19577283/28a7d8eb-c35a-4869-86b2-493a4ad0206e)

**Comment by Tormak9970** [comment]
> > @spineduke @anopem @Furglitch I'm having trouble reproducing this after making some other fixes, so I've released those fixes in [v3.6.5](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.6.5). Can yall test this again with the new update and let me know if the issue persists?
> 
> Unfortunetly it still persists for me, checked some works but didnt work for Back 4 Blood, Crysis 2 Remastered, Frostpunk, seems like the last version that works probably for me is 3.6.2
> 
> ![image](https://private-user-images.githubusercontent.com/19577283/331697936-28a7d8eb-c35a-4869-86b2-493a4ad0206e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzI2ODEsIm5iZiI6MTcxNTk3MjM4MSwicGF0aCI6Ii8xOTU3NzI4My8zMzE2OTc5MzYtMjhhN2Q4ZWItYzM1YS00ODY5LTg2YjItNDkzYTRhZDAyMDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE4NTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMDQ5MzI1ZmRhZDU4NzdlZDZiMzJjNDI5MjQ0MjU4NDBiMzIzY2FjZDBjNDhhZDA0Y2Y5MmVmN2ZmNTQ1ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.740iAOf0GlWgYoH-_4SjLfVo32QeZXX0ol6f2Qlx-1E)

I'll continue to look into it. Could you try using the [v3.6.4 debug](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/debug-3.6.4) release? Assuming you get the same error it'll tell us exactly where its occurring in the code

**Comment by anopem** [comment]
> > > @spineduke @anopem @Furglitch I'm having trouble reproducing this after making some other fixes, so I've released those fixes in [v3.6.5](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.6.5). Can yall test this again with the new update and let me know if the issue persists?
> > 
> > 
> > Unfortunetly it still persists for me, checked some works but didnt work for Back 4 Blood, Crysis 2 Remastered, Frostpunk, seems like the last version that works probably for me is 3.6.2
> > ![image](https://private-user-images.githubusercontent.com/19577283/331697936-28a7d8eb-c35a-4869-86b2-493a4ad0206e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzI2ODEsIm5iZiI6MTcxNTk3MjM4MSwicGF0aCI6Ii8xOTU3NzI4My8zMzE2OTc5MzYtMjhhN2Q4ZWItYzM1YS00ODY5LTg2YjItNDkzYTRhZDAyMDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE4NTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMDQ5MzI1ZmRhZDU4NzdlZDZiMzJjNDI5MjQ0MjU4NDBiMzIzY2FjZDBjNDhhZDA0Y2Y5MmVmN2ZmNTQ1ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.740iAOf0GlWgYoH-_4SjLfVo32QeZXX0ol6f2Qlx-1E)
> 
> I'll continue to look into it. Could you try using the [v3.6.4 debug](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/debug-3.6.4) release? Assuming you get the same error it'll tell us exactly where its occurring in the code


Heres the log
[tauri.localhost-1715973254539.log](https://github.com/Tormak9970/Steam-Art-Manager/files/15357466/tauri.localhost-1715973254539.log)

**Comment by Tormak9970** [comment]
> > > > @spineduke @anopem @Furglitch I'm having trouble reproducing this after making some other fixes, so I've released those fixes in [v3.6.5](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.6.5). Can yall test this again with the new update and let me know if the issue persists?
> > > 
> > > 
> > > Unfortunetly it still persists for me, checked some works but didnt work for Back 4 Blood, Crysis 2 Remastered, Frostpunk, seems like the last version that works probably for me is 3.6.2
> > > ![image](https://private-user-images.githubusercontent.com/19577283/331697936-28a7d8eb-c35a-4869-86b2-493a4ad0206e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzI2ODEsIm5iZiI6MTcxNTk3MjM4MSwicGF0aCI6Ii8xOTU3NzI4My8zMzE2OTc5MzYtMjhhN2Q4ZWItYzM1YS00ODY5LTg2YjItNDkzYTRhZDAyMDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE4NTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMDQ5MzI1ZmRhZDU4NzdlZDZiMzJjNDI5MjQ0MjU4NDBiMzIzY2FjZDBjNDhhZDA0Y2Y5MmVmN2ZmNTQ1ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.740iAOf0GlWgYoH-_4SjLfVo32QeZXX0ol6f2Qlx-1E)
> > 
> > 
> > I'll continue to look into it. Could you try using the [v3.6.4 debug](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/debug-3.6.4) release? Assuming you get the same error it'll tell us exactly where its occurring in the code
> 
> Heres the log [tauri.localhost-1715973254539.log](https://github.com/Tormak9970/Steam-Art-Manager/files/15357466/tauri.localhost-1715973254539.log)

can you screenshot the console? this appears to be a frontend error and isn't showing up in the log file for some reason

**Comment by Tormak9970** [comment]
wait nvm, misread the file

**Comment by anopem** [comment]
> wait nvm, misread the file

From what i can tell it finds no grids in filterGrids()

**Comment by Tormak9970** [comment]
yea, that's simply a filter function tho, so the main issue is likely in `fetchGridsForGame()` in the cache controller. I think it may be related to the page being fetched. I think I may have figured it out, need to test tho

**Comment by spineduke** [comment]
A bit late but also tried 3.6.5 and no luck. Doesn't pull any grids.

**Comment by Tormak9970** [comment]
Its skipping the first page occassionally, which would explain why only some games don't load

**Comment by anopem** [comment]
> Its skipping the first page occassionally, which would explain why only some games don't load

Yea that would make alot of sense ...

**Comment by spineduke** [comment]
You're onto something, cause the popular games do have some grids showing, so my guess is games with less than a page of grids won't return anything.

**Comment by Tormak9970** [comment]
yea I figured as much, which would explain why I didn't notice it. Even the indies I have are very mainstream. I'll work on getting that fixed today, hopefully will have a fix out by the end of the day

**Comment by Tormak9970** [comment]
fixed as of https://github.com/Tormak9970/Steam-Art-Manager/commit/9213bc14c9a035df53f1556d11f07b017c803881. There'll be an update available in 15 minutes or so.
