### ISSUE TITLE
Cannot select all above entries in batch mode

### ISSUE THREAD

**Issue by mdeguzis** [Tormak9970/Steam-Art-Manager#199]
**Describe the bug**

**To Reproduce**
1. Go to batch mode (bottom right)
2. Default is all games type, cannot select "only missing"
3. Switch to Steam type, select "only missing" - OK
4. Boxes turn to unchecked, but batching can being (so not sure what all it's going to process). Maybe a filtering issue in the UI?

**Expected behavior**
Only missing selection to show only what it will pull. There is no select all/none above the results (so you could unselect all and maybe just check a few of them). We need a way to check all / none yea. I understood the "missing" filter would be those that do not have capsule art (600x900), but it seems that list is the same as "ALL", but it removes the checkmarks.

**Screenshots**
Will add soon, on my laptop :)

**Logs:**

For Linux, check: `/home/USER/.config/dev.tormak.steam-art-manager/logs/core.log`

**System information (please complete the following information):**
 - OS: SteamOS 3
 - Version [e.g. v1.0.0]: 

**Additional information**
Add any other information about the problem here.

**Comment by mdeguzis** [comment]
Disregard I think, it does check the one that's truly missing. What I think happens, is it's those "covers" that are literally a shrunk down version of the wide (old style) cover in the center, and a blurred backgrounds. Would be nice to find a way to filter those, as those are the most prevalent offenders in libraries.

**Comment by Tormak9970** [comment]
I'll look into a solution to filter those out

**Comment by mdeguzis** [comment]
Looks like the defaults are saved to `~/.steam/steam/appcache/librarycache`. The logic possibly could say if

```
if ! grep -q <IMAGE_NAME>.<EXT> ~/.local/share/Steam/userdata/<ID>/config/grid; then
    cover_missing=true
else
    cover_missing=false
fi

```

i.e. Do a comparison between the grid folder (which would be "extra images") and the default library cache.

**Comment by Tormak9970** [comment]
> Looks like the defaults are saved to `~/.steam/steam/appcache/librarycache`. The logic possibly could say if
> 
> 
> 
> ```
> 
> if ! grep -q <IMAGE_NAME>.<EXT> ~/.local/share/Steam/userdata/<ID>/config/grid; then
> 
>     cover_missing=true
> 
> else
> 
>     cover_missing=false
> 
> fi
> 
> 
> 
> ```
> 
> 
> 
> Those file formats are:
> 
> 
> 
> * `<GAME_ID>_header.jpg`
> 
> * `<GAME_ID>_icon.jpg`
> 
> * `<GAME_ID>_library_600x900.jpg`
> 
> * `<GAME_ID>_library_hero_blur.jpg`
> 
> * `<GAME_ID>_library_hero.jpg`
> 
> * `<GAME_ID>_logo.jpg`
> 
> 
> 
> i.e. Do a comparison between the grid folder (which would be "extra images") and the default library cache. 
> 
> 
> 
> In the test case of "A virus named Tom" here, this is what exists in library cache by default:
> 
> 
> 
> ![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/3931917/6b1a3d26-fbaa-47a6-9f5b-58267b161211)
> 
> 
> 
> That `<GAME_ID>_library_600x900.jpg` is the one used. It can be a full cover, e.g. A Hat in Time, or a "fake cover" like A Virus Named Tom.
> 
> 
> 
> ![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/3931917/afd84c2d-1e54-41f3-b540-9964bc7cb8e9)
> 
> 

Its a solid idea but unfortunately that wont work. The purpose is to set all games with no grids, so that needs to take account for games with custom grids. I'm thinking maybe showing a preview or something might help when the user is making their selection

**Comment by mdeguzis** [comment]
In the meantime, I found some code and will just tinker around with VDF/SteamGridDB for fun https://github.com/mdeguzis/python-steamgriddy. Appreciate all the help!

**Comment by mdeguzis** [comment]
A fun idea I am going to tinker with (if I can figure it out lol), is doing an OCR search. It might be magically possible to just open the header image an OCR search the `<ID>_library_600x900.jpg` file to see if it matches. Wild Idea LOL.  Going to recheck some things to see how the library cache differs from the grid folder. The grid folder just seems to override what Steam sees in the library cache folder.

**Comment by mdeguzis** [comment]
@Tormak9970 I played around with Python OCR tools. I know you probably won't use this, but it is definitely possible to make the image comparison to determine if it's the "crap default fake capsule image".

Code: https://github.com/mdeguzis/python-steamgriddy/blob/main/utils/ocr-test.py

The OCR check:

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/3931917/1bc06a94-a57b-4ee9-8b59-84fda38fa5ea)

It's pretty cool

**Comment by Tormak9970** [comment]
> @Tormak9970 I played around with Python OCR tools. I know you probably won't use this, but it is definitely possible to make the image comparison to determine if it's the "crap default fake capsule image".
> 
> 
> 
> Code: https://github.com/mdeguzis/python-steamgriddy/blob/main/utils/ocr-test.py
> 
> 
> 
> The OCR check:
> 
> 
> 
> Check if source:
> 
> 
> 
> ![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/3931917/832e274d-4eb8-4e50-9da6-bc1226c22776)
> 
> 
> 
> Exists in target:
> 
> 
> 
> ![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/3931917/00b2d079-f69f-41c0-b76b-0b50c2a3e3e8)
> 
> 
> 
> 
> 
> ![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/3931917/1bc06a94-a57b-4ee9-8b59-84fda38fa5ea)
> 
> 
> 
> It's pretty cool

That's neat but I probably wont use it as its not really in scope and would require a performance hit and python sidecar

**Comment by mdeguzis** [comment]
No problem, just wanted to share a possible method. It didn't introduce any noticeable slowdown when processing my 700+ games. I'll keep this to my one off tool then.
