### ISSUE TITLE
Panic due to New AppInfo.vdf Magic Header

### ISSUE THREAD

**Issue by SillyNewb** [Tormak9970/Steam-Art-Manager#205]
**Describe the bug**

**To Reproduce**
1. Open SARM
2. See Error

**Expected behavior**
Unable to properly open SARM. Reinstalled both Steam and SARM and the same error occurs.

**Screenshots**

**Logs:**
Please upload/paste the contents of your log file (you should remove any sensitive information like keys).
**PRE v2.2.0**:
[Steam Art Manager] [11:9:34] [INFO]: Initialized logging file
[Steam Art Manager] [11:9:34] [INFO]: Finished checking settings for new app version and/or migration.
[Steam Art Manager] [11:9:34] [INFO]: Added c:/program files (x86)/steam to scope.
[Steam Art Manager] [11:9:34] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [11:9:34] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [11:9:34] [WARNING]: The SteamGridDB API key found in settings is no longer valid.
[Steam Art Manager] [11:9:34] [INFO]: Loaded 0 custom game names.
[Steam Art Manager] [11:9:34] [INFO]: Finished loading app settings.
[Steam Art Manager] [11:9:34] [INFO]: App setup complete.
[Steam Art Manager] [11:9:34] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [11:9:34] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [11:9:34] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [11:9:34] [INFO]: Added c:/program files (x86)/steam to scope.
[Steam Art Manager] [11:9:34] [INFO]: Updated setting steamInstallPath to "C:/Program Files (x86)/Steam".
[Steam Art Manager] [11:9:34] [INFO]: Updated setting debugMode to false.
[Steam Art Manager] [11:9:34] [INFO]: Loaded non-steam games.
[Steam Art Manager] [11:9:34] [INFO]: Getting steam grids folder...
[Steam Art Manager] [11:9:34] [INFO]: Initialized CacheController.
[Steam Art Manager] [11:9:34] [INFO]: Grids loaded.
[Steam Art Manager] [11:9:34] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [11:9:35] [INFO]: Library Cache loaded.
[Steam Art Manager] [11:9:35] [INFO]: Cached logo positions for 0 games.
[Steam Art Manager] [11:9:35] [ERROR]: Cannot read properties of null (reading 'game')
[Steam Art Manager] [11:9:35] [INFO]: Getting steam appinfo.vdf...
[Steam Art Manager] [11:9:35] [ERROR]: PANIC: File 'src\appinfo_vdf_parser.rs' at line 35: Magic header is unknown. Expected 0x07564428 or 0x07564427 but got 123094057
[Steam Art Manager] [11:9:35] [ERROR]: Please open an issue at https://github.com/Tormak9970/Steam-Art-Manager/issues
[Steam Art Manager] [11:9:46] [INFO]: Reverting settings...
[Steam Art Manager] [11:9:46] [INFO]: Reverted settings.
[Steam Art Manager] [11:9:56] [INFO]: Updated setting showHiddenGames to true.
[Steam Art Manager] [11:9:57] [INFO]: Updated setting windowSettings.main.gameViewType to 1.

For Windows, check: `C:\Users\USER\AppData\Roaming\dev.tormak.steam-art-manager\logs\steam-art-manager.log`
For Linux, check: `/home/USER/.config/dev.tormak.steam-art-manager/logs/steam-art-manager.log`
**NEWER VERSIONS**:
For Windows, check: `C:\Users\USER\AppData\Roaming\dev.tormak.steam-art-manager\logs\core.log`
For Linux, check: `/home/USER/.config/dev.tormak.steam-art-manager/logs/core.log`

**System information (please complete the following information):**
 - OS: W11
 - Version 23H2

**Additional information**
Add any other information about the problem here.

**Comment by Tormak9970** [comment]
This is the same issue as https://github.com/Tormak9970/Steam-Art-Manager/issues/204. I've fixed it. Just making a few additional fixes to speed up load times and then I'll make a new release

**Comment by Tormak9970** [comment]
fix is included in the next release
