### ISSUE TITLE
No images loading v3.10

### ISSUE THREAD

**Issue by anopem** [Tormak9970/Steam-Art-Manager#212]
**Describe the bug**
There is no images shown for the games grid when starting the app.

I removed the old version manually and installed the new one

![image](https://github.com/user-attachments/assets/e75a68b8-a7b1-4f7d-a247-060550644a57)

Edit:
added console log:
`main-BgM8fyYq.js:4  SARM  INFO  Finished checking settings for new app version and/or migration.
main-BgM8fyYq.js:4  SARM  INFO  Initialized CacheController.
main-BgM8fyYq.js:4  SARM  INFO  Loaded 3 manually added games.
main-BgM8fyYq.js:4  SARM  INFO  Loaded 7 custom game names.
main-BgM8fyYq.js:4  SARM  INFO  Finished loading app settings.
main-BgM8fyYq.js:4  SARM  INFO  App setup complete.
main-BgM8fyYq.js:4  SARM  INFO  App loaded. IsOnline: true.
main-BgM8fyYq.js:4  SARM  INFO  Updated setting steamInstallPath to "C:/Program Files (x86)/Steam".
main-BgM8fyYq.js:4  SARM  INFO  Updated setting debugMode to false.
main-BgM8fyYq.js:4  SARM  INFO  Updated setting windowSettings.main.panels to {"options":15,"games":40.28750900576369,"grids":44.71249099423631}.
main-BgM8fyYq.js:4  SARM  INFO  Loaded 827 games from Steam API.
main-BgM8fyYq.js:4  SARM  INFO  Cached logo positions for 87 games.
196Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' asset: <URL> <URL>".

main-BgM8fyYq.js:4  SARM  INFO  Updated setting hiddenGameIds to [993090,1235910].
main-BgM8fyYq.js:4  SARM  INFO  Updated setting hiddenGameIds to [993090].
main-BgM8fyYq.js:4  SARM  INFO  Prompting user to export.
main-BgM8fyYq.js:4  SARM  INFO  Export grids cancelled.
main-BgM8fyYq.js:4  SARM  INFO  Finding SGDB game for 251570...
main-BgM8fyYq.js:4  SARM  INFO  Fetching grids for game 251570...
main-BgM8fyYq.js:4  SARM  INFO  Need to fetch page 0 of Capsule for 3053.
main-BgM8fyYq.js:4  SARM  INFO  Query: "Capsules for 7 Days to Die". Result: 46 grids.
main-BgM8fyYq.js:4  SARM  INFO  Finding SGDB game for 397270...
main-BgM8fyYq.js:4  SARM  INFO  Fetching grids for game 397270...
main-BgM8fyYq.js:4  SARM  INFO  Need to fetch page 0 of Capsule for 8902.
main-BgM8fyYq.js:4  SARM  INFO  Query: "Capsules for A Kiss For The Petals - Remembering How We Met". Result: 3 grids.
main-BgM8fyYq.js:4  SARM  INFO  Finding SGDB game for 555630...
main-BgM8fyYq.js:4  SARM  INFO  Fetching grids for game 555630...
main-BgM8fyYq.js:4  SARM  INFO  Need to fetch page 0 of Capsule for 15253.
main-BgM8fyYq.js:4  SARM  INFO  Query: "Capsules for A Magical High School Girl". Result: 1 grids.
main-BgM8fyYq.js:4  SARM  INFO  Finding SGDB game for 609320...
main-BgM8fyYq.js:4  SARM  INFO  Fetching grids for game 609320...
main-BgM8fyYq.js:4  SARM  INFO  Need to fetch page 0 of Capsule for 17403.
main-BgM8fyYq.js:4  SARM  INFO  Query: "Capsules for FAR: Lone Sails". Result: 15 grids.`

**Comment by Tormak9970** [comment]
Hmm, I'll take a look at it when I get a chance. It should still save changes you make

**Comment by Tormak9970** [comment]
@anopem what platform are you on?

**Comment by Tormak9970** [comment]
fixed the issue. will push out a bugfix
