### ISSUE TITLE
SARM infinite loads

### ISSUE THREAD

**Issue by madok15** [Tormak9970/Steam-Art-Manager#218]
As the title says, the Steam Art Manager infinite loads even when uninstalling it, even the menu doesn't load and it's broken when adding Steam file address and all. Using Windows 11 24H2.
![Screenshot 2024-10-28 005008](https://github.com/user-attachments/assets/1906c20c-8c4a-42c0-9bea-ea03c502dbf5)

**Comment by madok15** [comment]
yes, this is the latest version. Even when downgrading versions.

**Comment by Tormak9970** [comment]
Can you try what I mentioned here: https://github.com/Tormak9970/Steam-Art-Manager/issues/216#issuecomment-2441780243

**Comment by madok15** [comment]
nope, also, it was in AppData/Local, but yea, that didn't fix anything.

**Comment by Tormak9970** [comment]
> nope, also, it was in AppData/Local, but yea, that didn't fix anything.

The file I was referring to is in Roaming, Local has a folder. You you have file extensions enabled in your File Explorer?

**Comment by madok15** [comment]
ah, found it, and yea, that actually fixed it. it was in Roaming and it was a file.
