### ISSUE TITLE
Import not working in 3.10.x

### ISSUE THREAD

**Issue by Dogo314** [Tormak9970/Steam-Art-Manager#219]
**Describe the bug**
Import zip file made in 3.6.x  not working in 3.10.x versions. Windows 10.

**To Reproduce**
With 3.6.8 version, update though program or downloading new version.
Import zip file.
No changes reflected in the program's covers.

**Comment by Tormak9970** [comment]
I'll look into this and try to get a fix out soon

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/Steam-Art-Manager/commit/c4313fa662bda3902ac61e953afe68ff2c5d1150

**Comment by Dogo314** [comment]
Working as expected!
