### ISSUE TITLE
Steam Art Manager (AppImage) does not show anything

### ISSUE THREAD

**Issue by pc-v2** [Tormak9970/Steam-Art-Manager#228]
**Describe the bug**
Steam Art Manager (AppImage) does not show anything, I use the latest script

**To Reproduce**
1. download the latest script and set executable property
2. ./appimage_installer.sh
3. Installing
4. Open Steam Art Manager
5. Does not show anything 

**Expected behavior**
Steam Art Manager display the app content

**Screenshots**

![image](https://github.com/user-attachments/assets/c11e4039-03ab-46ce-9cda-87e4da3ead24)

**Logs:**
Please upload/paste the contents of your log file (you should remove any sensitive information like keys).

```
elgato ➜ ~/.sarm $ ./steam-art-manager.AppImage
Gtk-Message: 12:37:35.849: Failed to load module "appmenu-gtk-module"
Gtk-Message: 12:37:36.057: Failed to load module "appmenu-gtk-module"
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...

** (app:33240): WARNING **: 12:38:00.969: atk-bridge: get_device_events_reply: unknown signature
```

**System information (please complete the following information):**
 - OS: Nobara KDE
 - Version: 40

**Additional information**
os is already updated to latest update

**Comment by pc-v2** [comment]
update: It works fine if I run the binary

**Comment by Tormak9970** [comment]
This seems like it is a tauri issue (since its related to gtk), but since its working when running the binary, not sure what happened. Glad its working though
