### ISSUE TITLE
Grid image preview shows default

### ISSUE THREAD

**Issue by anopem** [Tormak9970/Steam-Art-Manager#229]
The grid images always shows Steams default images on load and only changes when i apply new ones, it shows default again on next restart and not the custom ones, this stopped working after version 3.6.8 for me

**Comment by Tormak9970** [comment]
> The grid images always shows Steams default images on load and only changes when i apply new ones, it shows default again on next restart and not the custom ones, this stopped working after version 3.6.8 for me

Do you mean the grid preview feature isn't updating, or that the grids for each game aren't correct initially

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/Steam-Art-Manager/commit/c854bf5c3c6ba6e07891429747ffe85f9db778a5.
