### ISSUE TITLE
Compatibility with Steam Family Library Games

### ISSUE THREAD

**Issue by RobotCGB** [Tormak9970/Steam-Art-Manager#234]
Recognize and allow to change the art in the games acquired by the Steam Family feature.

**Comment by Tormak9970** [comment]
> Recognize and allow to change the art in the games acquired by the Steam Family feature.

I can look into this but as far as I'm aware there's no easy way to detect them. For now you should be able to add them manually using the search feature

**Comment by RobotCGB** [comment]
Great, that makes it work!! Thanks for the quick response and this useful program ;)
