### ISSUE TITLE
Some games are not detected in the application for Windows10 (MSI) & Steam Deck (Appimage)

### ISSUE THREAD

**Issue by dtantono** [Tormak9970/Steam-Art-Manager#62]
Hi
I have some games that are not detected and I think this app still have stability issue. What do you think?

**Comment by Tormak9970** [comment]
Can you provide examples of the games? It has worked flawlessly for me

**Comment by dtantono** [comment]
Hi
I just realized that on first time setup when I turn on the app and enter steamgrid API for the first time. I need to close the app and Steam and I need to turn both of these apps again to make it appears Can you update the documentation please?

**Comment by Tormak9970** [comment]
> Hi I just realized that on first time setup when I turn on the app and enter steamgrid API for the first time. I need to close the app and Steam and I need to turn both of these apps again to make it appears Can you update the documentation please?

please open a new issues for this

**Comment by Tormak9970** [comment]
Closing this in favor of issue Tormak9970/Steam-Art-Manager#65
