### ISSUE TITLE
The app is very slow to start and sometimes does not start at all (Windows10)

### ISSUE THREAD

**Issue by dtantono** [Tormak9970/Steam-Art-Manager#63]
Hi
I tried the app on Windows. But, sometimes it does not start at all and I need to start the app many times. Is it a bug?

**Comment by Tormak9970** [comment]
> Hi I tried the app on Windows. But, sometimes it does not start at all and I need to start the app many times. Is it a bug?

Didn't occur in my testing, but is definitely a bug, will look into it

**Comment by Tormak9970** [comment]
This has been fixed and will be included in the next release
