### ISSUE TITLE
Add feature to customise artworks for non Steam games/applications

### ISSUE THREAD

**Issue by dtantono** [Tormak9970/Steam-Art-Manager#66]
hi
This app is great and I hope we can customise artworks for non steam games/applications as well. what do you think?

**Comment by Tormak9970** [comment]
> hi This app is great and I hope we can customise artworks for non steam games/applications as well. what do you think?

This is planned. Currently have other issues that need tending to but it should be included in the next release

**Comment by Tormak9970** [comment]
This has been implemented and will be included in the next release
