### ISSUE TITLE
Feature Request: Mass download

### ISSUE THREAD

**Issue by JohnGhostly** [Tormak9970/Steam-Art-Manager#77]
I think it would be nice to be able to have the tool automatically pick images based on a filter. say if you want to automatically have square grids by default.

**Comment by Tormak9970** [comment]
> I think it would be nice to be able to have the tool automatically pick images based on a filter. say if you want to automatically have square grids by default. 

To clarify, you mean like a button to apply a grid for each game that matches the current filters?

**Comment by octopuserectus** [comment]
I agree, something like this would be nice. Essentially a "quick fix" for the library. Let's take a look at any "older" game which doesn't have all the images: capsule, logo (hero needs replacing too in such cases). I have hundreds of those. I would trust the app to pick most upvoted options (taking filters in mind) so the library looks neat. If it picks something bad-no big deal, still much better than doing it one by one.

**Comment by Tormak9970** [comment]
> I agree, something like this would be nice. Essentially a "quick fix" for the library. Let's take a look at any "older" game which doesn't have all the images: capsule, logo (hero needs replacing too in such cases). I have hundreds of those. I would trust the app to pick most upvoted options (taking filters in mind) so the library looks neat. If it picks something bad-no big deal, still much better than doing it one by one. 

Here's what I'm thinking. Have a button that says something like "fix library", and when clicked, gives you the option for either applying a grid (based on what type is currently selected,and filters) to every game, or just ones with a missing grid.

**Comment by Tormak9970** [comment]
Closing this as I have finished implementing it and it will be included in the update that goes live later today. Feel free to provide feedback on its functionality once you try it
