### ISSUE TITLE
Steam Art Manager 2.1.2 cannot save SteamGrid and Steam API Key (Windows 10& Ubuntu)

### ISSUE THREAD

**Issue by dtantono** [Tormak9970/Steam-Art-Manager#78]
Hi
I tried to input my steam grid api key and steam api key. But, when I click save and restart the app. it just disappear. What do you think?

**Comment by Tormak9970** [comment]
> Hi
> I tried to input my steam grid api key and steam api key. But, when I click save and restart the app. it just disappear. What do you think?

Try not restartibg after, that isnt necessary

**Comment by dtantono** [comment]
So, after I input the steam grid api key and steam api key and click save. the API key that I inserted before will be invisible, Is that so?

**Comment by Tormak9970** [comment]
> So, after I input the steam grid api key and steam api key and click save. the API key that I inserted before will be invisible, Is that so?

That shouldn't be happening. Can you open `/home/USER/.config/dev.tormak.steam-art-manager/settings.json` and see if they keys are in that file? If they aren't, try putting them in there manually, then open the app.

**Comment by dtantono** [comment]
yes, the keys are invisible on the menu. But, it is present on /home/USER/.config/dev.tormak.steam-art-manager/settings.json
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/29157187/32951c00-1aa7-4025-9bbe-52efbaf38d1c)
![2023-05-13_08-36](https://github.com/Tormak9970/Steam-Art-Manager/assets/29157187/1c8c703c-c05c-44e9-b751-b0302ed37de0)

**Comment by Tormak9970** [comment]
> yes, the keys are invisible on the menu. But, it is present on /home/USER/.config/dev.tormak.steam-art-manager/settings.json
> ![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/29157187/32951c00-1aa7-4025-9bbe-52efbaf38d1c)
> ![2023-05-13_08-36](https://github.com/Tormak9970/Steam-Art-Manager/assets/29157187/1c8c703c-c05c-44e9-b751-b0302ed37de0)
> 

Odd, it should show up then. Are you able to browse images, or is the app saying it needs the api key still?

**Comment by dtantono** [comment]
yeah only for SteamOS and not for other distros

**Comment by Tormak9970** [comment]
> yeah only for SteamOS and not for other distros

Does it load your games?

**Comment by dtantono** [comment]
for steamos, it loads for 2.1.2. But, for other distro (i use Ubuntu) I need to downgrade to 2.1.0. What do you think?

**Comment by Tormak9970** [comment]
@dtantono It appears there was an issue with saving the Steam API key. I've resolved it, and it will be included in the next release, but I would like you to try the [debug](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/debug-2.1.2) release that has the fix, so I know if it solves your issue
