### ISSUE TITLE
Steam Art Manager 2.1.2 cannot load on Ubuntu 22.04

### ISSUE THREAD

**Issue by dtantono** [Tormak9970/Steam-Art-Manager#79]
Hi
I know there is similar case (https://github.com/Tormak9970/Steam-Art-Manager/issues/65) and I believe it have been solved. But, the thing is I download v2.1.2. it took forever to load games from Steam APT (it works on SteamOS) and when I use v 2.1.0 it works again. What do you think?

**Comment by Tormak9970** [comment]
> Hi I know there is similar case (#65) and I believe it have been solved. But, the thing is I download v2.1.2. it took forever to load games from Steam APT (it works on SteamOS) and when I use v 2.1.0 it works again. What do you think?

To clarify, this worked on SteamOS but not ubuntu?

**Comment by dtantono** [comment]
yes, what do you think?

**Comment by Tormak9970** [comment]
> yes, what do you think?

Honestly, I have no idea. I have no way to test Ubuntu, but the linux buikds for all distros are built on an ubuntu server so I would thibk it would work. Can you upload your log file? Should be `/home/USER/.config/dev.tormak.steam-art-manager/logs/steam-art-manager.log`

**Comment by dtantono** [comment]
here it is
[steam-art-manager.log](https://github.com/Tormak9970/Steam-Art-Manager/files/11468521/steam-art-manager.log)

**Comment by Tormak9970** [comment]
> here it is [steam-art-manager.log](https://github.com/Tormak9970/Steam-Art-Manager/files/11468521/steam-art-manager.log)

is this on one of the devices having issue #78?

**Comment by dtantono** [comment]
yes, it is related

**Comment by Tormak9970** [comment]
Ok. Closing this then, since its the same systems
