### ISSUE TITLE
Installed via the msi and the app instantly closes after launch

### ISSUE THREAD

**Issue by superusercode** [Tormak9970/Steam-Art-Manager#87]
**Describe the bug**
Installed via the msi and the app instantly closes after launch. Blocked me from adding the app to winget @ https://github.com/microsoft/winget-pkgs/pull/107125

**To Reproduce**
1. Use a clean install of windows 
2. Install SAM via the msi
3. Attempt to open it

**Expected behavior**
Launches

**Screenshots**
n/a

**Logs:**
Closes immediately so no events pop up in the log
**Additional information**
Add any other information about the problem here.

**Comment by Tormak9970** [comment]
> **Describe the bug** Installed via the msi and the app instantly closes after launch. Blocked me from adding the app to winget @ [microsoft/winget-pkgs#107125](https://github.com/microsoft/winget-pkgs/pull/107125)
> 
> **To Reproduce**
> 
>     1. Use a clean install of windows
> 
>     2. Install SAM via the msi
> 
>     3. Attempt to open it
> 
> 
> **Expected behavior** Launches
> 
> **Screenshots** n/a
> 
> **Logs:** Closes immediately so no events pop up in the log **Additional information** Add any other information about the problem here.

Wiped all dev related files from my pc (windows 10) and installed the msi, works perfectly, going to test on another device as well

**Comment by Tormak9970** [comment]
I'm not sure, I haven't used winget before

**Comment by Tormak9970** [comment]
Not sure what's causing it, it also works perfectly on my second pc (windows 10)

**Comment by Tormak9970** [comment]
@superusercode sanity check, do you have steam installed, I don't have a check in place for that

**Comment by Tormak9970** [comment]
> No, I don't have steam installed. That explains why it didn't launch then.

Lol, it never occurred to me that the app would be installed without steam already installed. I'll leave this open till I get around to adding that check
