### ISSUE TITLE
Fail to load or save changes

### ISSUE THREAD

**Issue by sharkiller** [Tormak9970/Steam-Art-Manager#89]
**Describe the bug**
When you open the app it always load on a "undefined" account and keep loading the games forever. 
If i change the account to my account in the menu, is does nothing. It keep loading.
If I open the settings and set the keys it does nothing. Click save doesnt even close the settings windows.
If I close the app and reopen the app, the keys are empty again.

**To Reproduce**
1. Open the app
2. Nothing works

**Expected behavior**
Works

**Screenshots**
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/fab9de39-c5be-41c7-8540-10e085a8bd96)
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/9a25bd32-688d-4dd0-a217-974334afdfbf)
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/a05df96d-19fc-4fca-957e-da77271de017)
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/13e028c0-5c43-439b-8fd4-f3870420e6a6)

**Logs:**
Please upload/paste the contents of your log file (you should remove any sensitive information like keys).
[Steam Art Manager] [17:33:11] [INFO]: Initialized logging file
[Steam Art Manager] [17:33:11] [INFO]: Added Steam directory to scope.
[Steam Art Manager] [17:33:11] [INFO]: Found cache dir.
[Steam Art Manager] [17:33:11] [INFO]: Found grids cache dir.
[Steam Art Manager] [17:33:11] [INFO]: Found Capsule cache dir.
[Steam Art Manager] [17:33:11] [INFO]: Found Wide Capsule cache dir.
[Steam Art Manager] [17:33:11] [INFO]: Found Hero cache dir.
[Steam Art Manager] [17:33:11] [INFO]: Found Logo cache dir.
[Steam Art Manager] [17:33:11] [INFO]: Found Icon cache dir.
[Steam Art Manager] [17:33:11] [INFO]: Initialized CacheController.
[Steam Art Manager] [17:33:15] [INFO]: Opening settings window.
[Steam Art Manager] [17:33:17] [INFO]: Closing settings window.
[Steam Art Manager] [17:36:43] [INFO]: Discarded changes.
[Steam Art Manager] [17:37:22] [INFO]: Opening settings window.
[Steam Art Manager] [17:37:42] [INFO]: Saving settings...
[Steam Art Manager] [17:38:17] [INFO]: Closing settings window.

**System information (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Version 2.3.0

**Additional information**
On a previous version have all the same errors, but after changing the undefined account and reloading the list it showed the games. 
This new version the reload button just reload the whole app so it never works.

**Comment by sharkiller** [comment]
I have ~700 games and ~900 dlcs. I dont know it could be related to that.

**Comment by Tormak9970** [comment]
It shouldnt be related to that, as long as your steam profile is public or you are using a Steam API key. Gonna have to look into this, cause I thought I verified settings were saving properly.

**Comment by sharkiller** [comment]
tried running the app with admin rights doest help.
tried deleting everything and reinstalling doesnt help either.  

should my account be selected by default? why it always select undefined when opening the app?

**Comment by Tormak9970** [comment]
yes, your account should be selected by default. I suspect this is an issue with your `C:/Program Files (x86)/Steam/config/loginusers.vdf` file. SARM expects one of the the users to have the `MostRecent` property set to 1. Can you check yours to see if that's the case? if not, try changing it with a text editor and seeing if it works. I'll add some systems to avoid this if so

**Comment by sharkiller** [comment]
@Tormak9970 loginusers is fine. only one user and it has the mostrecent set to 1.  
for your information the previous version "works", only 1 times but it works. it start as undefined and change the account and ask me for the api keys and the games are shown. 
but if you close the app and open it again it doesnt work anymore, again default account is undefined and if you change to my account it doesnt show the game, not even ask you for the api keys and if you open the settings the inputs are empty and even you fill them, they dont work.
2.3.0 it just never works. never ask you for api keys and even you fill them in settings they do nothing.  
odd thing is i open the settings files in appdata the api key are saved, but you open the app and nothing is set.

**Comment by sharkiller** [comment]
@Tormak9970 based on your suggestion i was reading your code and following the path with the code, I found that you check for "MostRecent" key and in loginuser.vdf is in "mostrecent" in lowercase. Changed to "MostRecent" and now the app works as expected.  
I never modified loginuser so that comes from steam app directly. you should check key without casematch or add a failsafe or a warning or at least log that no user was found with most recent.

**Comment by Tormak9970** [comment]
god damn it, figures. I didn't realize it could change cases like that. Will figure out how to account for that

**Comment by Tormak9970** [comment]
> @Tormak9970 loginusers is fine. only one user and it has the mostrecent set to 1. for your information the previous version "works", only 1 times but it works. it start as undefined and change the account and ask me for the api keys and the games are shown. but if you close the app and open it again it doesnt work anymore, again default account is undefined and if you change to my account it doesnt show the game, not even ask you for the api keys and if you open the settings the inputs are empty and even you fill them, they dont work. 2.3.0 it just never works. never ask you for api keys and even you fill them in settings they do nothing. odd thing is i open the settings files in appdata the api key are saved, but you open the app and nothing is set.

This isn't how its supposed to work. It should detect you automatically.

**Comment by Tormak9970** [comment]
> @Tormak9970 based on your suggestion i was reading your code and following the path with the code, I found that you check for "MostRecent" key and in my loginuser.vdf is "mostrecent" in lowercase. Changed to "MostRecent" and now the app works as expected. I never modified loginuser so that comes from steam app directly. you should check key without casematch or add a failsafe or a warning or at least log that no user was found with most recent key.

I've already added logging for when no users are found and a popup, will be included in the next version along with stuff to handle case mismatches

**Comment by Tormak9970** [comment]
Closing this as I have implemented a solution. Will be included in the next release
