### ISSUE TITLE
Applied art is not saved

### ISSUE THREAD

**Issue by RaptorTrap** [Tormak9970/Steam-Art-Manager#97]
**Describe the bug**
After setting some art, the green save button does nothing, no error is shown and the art is not applied.
Same issue for Steam and Non-Steam games.

**Logs:**

> [Steam Art Manager] [16:52:31] [INFO]: Initialized logging file
> [Steam Art Manager] [16:52:31] [INFO]: Added Steam directory to scope.
> [Steam Art Manager] [16:52:32] [INFO]: Initializing CacheController...
> [Steam Art Manager] [16:52:32] [INFO]: Checking config/loginusers.vdf for current user info.
> [Steam Art Manager] [16:52:32] [INFO]: Loaded 1 steam users.
> [Steam Art Manager] [16:52:32] [INFO]: Found cache dir.
> [Steam Art Manager] [16:52:32] [INFO]: Found grids cache dir.
> [Steam Art Manager] [16:52:32] [INFO]: Found Capsule cache dir.
> [Steam Art Manager] [16:52:32] [INFO]: App setup complete.
> [Steam Art Manager] [16:52:32] [INFO]: App loaded. IsOnline: true.
> [Steam Art Manager] [16:52:32] [INFO]: Loading non-steam games...
> [Steam Art Manager] [16:52:32] [INFO]: Getting steam shortcuts.vdf...
> [Steam Art Manager] [16:52:32] [INFO]: shortcuts.vdf exists, reading...
> [Steam Art Manager] [16:52:32] [INFO]: Loaded non-steam games.
> [Steam Art Manager] [16:52:32] [INFO]: Getting steam games...
> [Steam Art Manager] [16:52:32] [INFO]: Getting steam grids folder...
> [Steam Art Manager] [16:52:32] [INFO]: Found Wide Capsule cache dir.
> [Steam Art Manager] [16:52:32] [INFO]: Found Hero cache dir.
> [Steam Art Manager] [16:52:32] [INFO]: Grids loaded.
> [Steam Art Manager] [16:52:32] [INFO]: Getting steam library cache folder...
> [Steam Art Manager] [16:52:32] [INFO]: Found Logo cache dir.
> [Steam Art Manager] [16:52:32] [INFO]: Found Icon cache dir.
> [Steam Art Manager] [16:52:32] [INFO]: Initialized CacheController.
> [Steam Art Manager] [16:52:32] [INFO]: Library Cache loaded.
> [Steam Art Manager] [16:52:32] [INFO]: Cached logo positions for 15 games.
> [Steam Art Manager] [16:52:32] [INFO]: Loading games from Steam Community page...
> [Steam Art Manager] [16:52:33] [INFO]: Loaded 583 games from Steam Community page.
> [Steam Art Manager] [16:52:33] [INFO]: Steam games loaded.
> [Steam Art Manager] [16:52:42] [INFO]: Fetching grids for game 4165424554...
> [Steam Art Manager] [16:52:43] [INFO]: Need to fetch nonSteam Capsule for 35849.
> [Steam Art Manager] [16:52:43] [INFO]: Query: "Capsules for GZDoom". Result: 17 grids.
> [Steam Art Manager] [16:52:44] [INFO]: Fetching image https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/ffb556219a1a624b396d2b410766d75a.png...
> [Steam Art Manager] [16:52:44] [INFO]: Cache found. Fetching image from local file system.
> [Steam Art Manager] [16:52:44] [INFO]: Set Capsule for GZDoom (4165424554) to /home/deck/.cache/dev.tormak.steam-art-manager/grids/Capsule/ffb556219a1a624b396d2b410766d75a.png.
> [Steam Art Manager] [16:52:46] [INFO]: Saving changes...

**System information (please complete the following information):**
 - OS: Steam Deck 3.4.6
 - SARM Version 2.4

**Comment by Tormak9970** [comment]
Looks like there's a backend issue when saving art. Will look into it.

**Comment by Tormak9970** [comment]
@RaptorTrap I have done extensive testing on this and haven't been able to reproduce it. The next release will have better logging for the backend, and notify users if backend errors occur. I'm not going to close this yet because its not resolved, but once the new release is live, please update this issue if it occurs again

**Comment by Tormak9970** [comment]
The release with the improved logging is now live

**Comment by RaptorTrap** [comment]
Thank you, I tried it with the most recent 2.6 release but its still not working:

> [Steam Art Manager] [20:17:33] [INFO]: Initialized logging file
> [Steam Art Manager] [20:17:33] [INFO]: Added Steam directory to scope.
> [Steam Art Manager] [20:17:35] [INFO]: Initializing CacheController...
> [Steam Art Manager] [20:17:35] [INFO]: Checking config/loginusers.vdf for current user info.
> [Steam Art Manager] [20:17:35] [INFO]: Loaded 1 steam users.
> [Steam Art Manager] [20:17:35] [INFO]: Found cache dir.
> [Steam Art Manager] [20:17:35] [INFO]: Found grids cache dir.
> [Steam Art Manager] [20:17:35] [INFO]: Found Capsule cache dir.
> [Steam Art Manager] [20:17:35] [INFO]: App setup complete.
> [Steam Art Manager] [20:17:35] [INFO]: App loaded. IsOnline: true.
> [Steam Art Manager] [20:17:35] [INFO]: Loading non-steam games...
> [Steam Art Manager] [20:17:35] [INFO]: Getting steam shortcuts.vdf...
> [Steam Art Manager] [20:17:35] [INFO]: shortcuts.vdf exists, reading...
> [Steam Art Manager] [20:17:35] [INFO]: Loaded non-steam games.
> [Steam Art Manager] [20:17:35] [INFO]: Getting steam games...
> [Steam Art Manager] [20:17:35] [INFO]: Getting steam grids folder...
> [Steam Art Manager] [20:17:35] [INFO]: Found Wide Capsule cache dir.
> [Steam Art Manager] [20:17:35] [INFO]: Found Hero cache dir.
> [Steam Art Manager] [20:17:35] [INFO]: Grids loaded.
> [Steam Art Manager] [20:17:35] [INFO]: Getting steam library cache folder...
> [Steam Art Manager] [20:17:35] [INFO]: Found Logo cache dir.
> [Steam Art Manager] [20:17:35] [INFO]: Found Icon cache dir.
> [Steam Art Manager] [20:17:35] [INFO]: Initialized CacheController.
> [Steam Art Manager] [20:17:35] [INFO]: Library Cache loaded.
> [Steam Art Manager] [20:17:35] [INFO]: Cached logo positions for 15 games.
> [Steam Art Manager] [20:17:35] [INFO]: Loading games from Steam Community page...
> [Steam Art Manager] [20:17:38] [INFO]: Loaded 583 games from Steam Community page.
> [Steam Art Manager] [20:17:38] [INFO]: Steam games loaded.
> [Steam Art Manager] [20:17:44] [INFO]: Fetching grids for game 1294420...
> [Steam Art Manager] [20:17:45] [INFO]: Need to fetch nonSteam Capsule for 5332066.
> [Steam Art Manager] [20:17:45] [INFO]: Query: "Capsules for Rollerdrome". Result: 20 grids.
> [Steam Art Manager] [20:17:51] [INFO]: Fetching image https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/73c2fc802343d2e4316586f07b15d945.png...
> [Steam Art Manager] [20:17:51] [INFO]: Fetching image from API.
> [Steam Art Manager] [20:17:51] [INFO]: Downloading grid from https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/73c2fc802343d2e4316586f07b15d945.png to /home/deck/.cache/dev.tormak.steam-art-manager/grids/Capsule/73c2fc802343d2e4316586f07b15d945.png
> [Steam Art Manager] [20:17:53] [INFO]: Download of https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/73c2fc802343d2e4316586f07b15d945.png finished.
> [Steam Art Manager] [20:17:53] [INFO]: Set Capsule for Rollerdrome (1294420) to /home/deck/.cache/dev.tormak.steam-art-manager/grids/Capsule/73c2fc802343d2e4316586f07b15d945.png.
> [Steam Art Manager] [20:17:57] [INFO]: Saving changes...
> [Steam Art Manager] [20:18:0] [INFO]: Saving changes...

**Comment by Tormak9970** [comment]
@RaptorTrap does this happen for every game? So far I have not been able to reproduce the issue

**Comment by RaptorTrap** [comment]
Yes, with Steam and Non-Steam games.

**Comment by sharkiller** [comment]
Fyi saving was working for me on 2.5 and previous versions.

**Comment by sharkiller** [comment]
@Tormak9970 opened the console and there is an error when saving after changing the image of any app:

```
main-6c1e130c.js:9010  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nHeightPct')
    at HTMLButtonElement.saveChanges (main-6c1e130c.js:9010:19)
    at HTMLButtonElement.<anonymous> (main-6c1e130c.js:9491:20)
```
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/61899c26-def4-4b75-a4ff-031058e92ba7)

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/817a76e6-992f-4b0c-aeaa-97ebc1758893)

**Comment by Tormak9970** [comment]
> @Tormak9970 opened the console and there is an error when saving after changing the image of any app:
> 
> ```
> main-6c1e130c.js:9010  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nHeightPct')
>     at HTMLButtonElement.saveChanges (main-6c1e130c.js:9010:19)
>     at HTMLButtonElement.<anonymous> (main-6c1e130c.js:9491:20)
> ```
> 
> ![image](https://user-images.githubusercontent.com/712193/244876480-61899c26-def4-4b75-a4ff-031058e92ba7.png)
> 
> ![image](https://user-images.githubusercontent.com/712193/244876458-817a76e6-992f-4b0c-aeaa-97ebc1758893.png)

this is super helpful! Appears to be an issue with the logo position stuff. I'll try to get it fixed today

**Comment by sharkiller** [comment]
@Tormak9970 I added a breakpoint and some app dont have a logo position:

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/f56eb2b4-26fd-4d48-b01a-6523a3d05635)

**Comment by Tormak9970** [comment]
> @Tormak9970 I added a breakpoint and some app dont have a logo position:
> 
> ![image](https://user-images.githubusercontent.com/712193/244876645-f56eb2b4-26fd-4d48-b01a-6523a3d05635.png)

this is great! I suspect there is a bug related to how I'm loading the custom logo positions

**Comment by Tormak9970** [comment]
I believe I've fixed this, building a new debug release now

**Comment by Tormak9970** [comment]
@sharkiller and @RaptorTrap, can you both try the most recent debug release [here](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/debug-2.6.1)?

**Comment by sharkiller** [comment]
@Tormak9970 yeah i found that config/grid/ there was a 113020.json for "monaco" game that only had "{"nVersion":1}" in it, deleted the file and not it works.

**Comment by Tormak9970** [comment]
> @Tormak9970 yeah i found that config/grid/ there was a 113020.json for "monaco" game that only had "{"nVersion":1}" in it, deleted the file and not it works.

Ahh. New release has a check for malformed logo configs as well

**Comment by sharkiller** [comment]
@Tormak9970 re added the deleted file and now fails on another part at the end of the save function.

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/07b92789-06a9-431c-b903-fd9d5fffc45a)

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/3259555a-6b4d-44de-8fd3-c372ad89f4d7)

**Comment by sharkiller** [comment]
This is an edge case. Because I modified the position of the logo of the monaco game in steam and the json now have all the proper config.
If i just click modify logo position in steam and move nothing and just save, it update the json with the correct position.
If i reset the position of the logo on steam, the json file just get deleted. 

Maybe in a previous version it didnt delete the position and just updated the json, i dont know. I dont even remember changing something related to monaco logo.

**Comment by Tormak9970** [comment]
> This is an edge case. Because I modified the position of the logo of the monaco game in steam and the json now have all the proper config. If i just click modify logo position in steam and move nothing and just save, it update the json with the correct position. If i reset the position of the logo on steam, the json file just get deleted.
> 
> Maybe in a previous version it didnt delete the position and just updated the json, i dont know. I dont even remember changing something related to monaco logo.

Yes, I know, but I need to account for it because other users won't know that

**Comment by sharkiller** [comment]
@Tormak9970 also dont know if you changed anything, but the last debug you shared, every time you open the app is ultra small

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/712193/f5a6ebc3-d5c3-4912-9e7e-433544e6bf07)

and when you try to make it bigger it fixes the proper width and height.

**Comment by Tormak9970** [comment]
hmm, didn't touch anything related to that. lmk know if it happens with the next release i'm about to make

**Comment by sharkiller** [comment]
all fixed with 2.6.3

**Comment by RaptorTrap** [comment]
Yeah, found the issue earlier today, but didn't have time to make a PR. Empty json files were the culprit.
Working perfectly with 2.6.3, thanks everyone!

**Comment by Tormak9970** [comment]
Awesome, will make a stable release
